ads/urls.py
from django.urls import path
from .views import *

app_name = 'ads'

urlpatterns = [
    path('', CategoriesList.as_view(), name='categories_list'),
    path('add/', AddCategoryForm.as_view(), name='category_add'),
    path('<str:category>/edit/', EditCategoryForm.as_view(), name='category_edit'),
    path('<str:category>/add/', AddAdvertisementForm.as_view(), name='advertisement_add'),
    path('<str:category>/', AdvertisementsList.as_view(), name='advertisements_list'),
    path('<str:category>/<int:ad_id>/', AdvertisementDetail.as_view(), name='advertisement_detail'),
    path('<str:category>/<int:ad_id>/edit/', EditAdvertisementForm.as_view(), name='advertisement_edit'),
    # path('home/', HomePage.as_view(), name='home_page'),
]

bboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ads.urls', namespace='ads')),
]

ads/models.py
from django.db import models
from django.core import validators
from decimal import Decimal

class Category(models.Model):

    name = models.CharField(max_length=100, unique=True)
    desc = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Advertisement(models.Model):

    subject = models.CharField(max_length=300)
    text = models.TextField()
    cost = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        validators=[
            validators.MinValueValidator(limit_value=Decimal('0.01'))
        ],
        error_messages={
            'min_value': 'Cost can\'t be less than 0.01'
        }
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, default=None)

    class Meta:
        verbose_name = "Advertisement"
        verbose_name_plural = "Advertisements"

    def __str__(self):
        return self.subject

ads/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from ads.models import Category, Advertisement
from django.urls import reverse_lazy
from django.shortcuts import redirect

class CategoriesList(ListView):
    template_name = 'ads/categories_list.html'

    def get_queryset(self):
        return Category.objects.all().order_by('-updated')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cats'] = self.get_queryset()
        return context

    def post(self, request, *args, **kwargs):
        cat = Category.objects.get(id=request.POST['category'])
        cat.delete()
        return self.get(request, *args, **kwargs)


class AdvertisementsList(ListView):
    template_name = 'ads/advertisements_list.html'
    paginate_by = 4
    page_kwarg = 'page'

    def get_queryset(self):
        cat_name = Category.objects.get(name=self.kwargs['category'])
        return Advertisement.objects.filter(category=cat_name).order_by('-updated')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ads'] = self.get_queryset()
        context['current_category'] = self.kwargs['category']
        return context

    def post(self, request, *args, **kwargs):
        ad = Advertisement.objects.get(id=request.POST['ad_id'])
        ad.delete()
        return self.get(request, *args, **kwargs)


class AdvertisementDetail(DetailView):
    model = Advertisement
    slug_url_kwarg = 'ad_id'
    slug_field = 'id'
    query_pk_and_slug = True
    template_name = 'ads/advertisement_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ad = Advertisement.objects.get(id=self.kwargs['ad_id'])
        cat = Category.objects.get(name=ad.category)
        context['current_category'] = cat.name
        return context

    def post(self, request, *args, **kwargs):
        ad = Advertisement.objects.get(id=request.POST['ad_id'])
        cat = ad.category.name
        ad.delete()
        return redirect(reverse_lazy('ads:advertisements_list', kwargs={'category': cat}))


class HomePage(TemplateView):
    template_name = 'ads/home_page.html'


class AddCategoryForm(CreateView):
    template_name = 'ads/category_add.html'
    success_url = reverse_lazy('ads:categories_list')
    model = Category
    fields = [
        'name',
        'desc',
    ]


class EditCategoryForm(UpdateView):
    template_name = 'ads/category_edit.html'
    success_url = reverse_lazy('ads:categories_list')
    model = Category
    fields = [
        'name',
        'desc',
    ]
    slug_url_kwarg = 'category'
    slug_field = 'name'
    query_pk_and_slug = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_category'] = self.kwargs['category']
        return context


class AddAdvertisementForm(CreateView):
    template_name = 'ads/advertisement_add.html'
    model = Advertisement
    fields = [
        'subject',
        'text',
        'cost',
        'category',
    ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cat = Category.objects.get(name=self.kwargs['category'])
        context['cat'] = cat
        context['current_category'] = cat.name
        return context

    def get_success_url(self):
        cat_name = self.kwargs['category']
        return reverse_lazy('ads:advertisements_list', kwargs={'category': cat_name})


class EditAdvertisementForm(UpdateView):
    template_name = 'ads/advertisement_edit.html'
    model = Advertisement
    fields = [
        'subject',
        'text',
        'cost',
        'category',
    ]
    slug_url_kwarg = 'ad_id'
    slug_field = 'id'
    query_pk_and_slug = True

    def get_success_url(self):
        ad_id = self.kwargs['ad_id']
        ad = Advertisement.objects.get(id=self.kwargs['ad_id'])
        cat_name = ad.category
        return reverse_lazy('ads:advertisement_detail', kwargs={'ad_id': ad_id, 'category':cat_name})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ad = Advertisement.objects.get(id=self.kwargs['ad_id'])
        cat = Category.objects.get(name=ad.category)
        context['current_category'] = cat.name
        return context

ads/templates/ads/advertisement_add.html
{% extends 'ads/layout/base.html' %}

{% block title %}Add advertisement{% endblock title %}

{% block header %}Add advertisement{% endblock header %}

{% block main %}
<form method="post" class="p-6">
    {% csrf_token %}

    <div class="field">
        <label class="label" for="subject">Subject</label>
        <div class="control">
            <input class="input" type="text" name="subject" id="subject">
        </div>
    </div>

    <div class="field">
        <label class="label" for="text">Text</label>
        <div class="control">
            <textarea class="textarea" name="text" id="text" cols="30" rows="10"></textarea>
        </div>
    </div>

    <div class="field">
        <label class="label" for="cost">Cost</label>
        <div class="control">
            <input class="input" type="number" name="cost" id="cost" step="0.01" min="0.01">
        </div>
    </div>

    <input type="hidden" name="category" value="{{ cat.id }}">

    <div class="field">
        <div class="control">
            <input class="button is-primary" type="submit" value="Submit">
        </div>
    </div>
</form>
{% endblock main %}

ads/templates/ads/advertisement_detail.html
{% extends 'ads/layout/base.html' %}

{% block title %}{{ advertisement.subject }}{% endblock title %}

{% block header %}{{ advertisement.subject|capfirst }}{% endblock header %}

{% block top-menu-left %}
<div class="navbar-item">
    <div class="buttons">
        <a class="button is-warning is-light" href="{% url 'ads:advertisement_edit' ad_id=advertisement.id category=advertisement.category.name %}">Edit</a>
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="ad_id" value="{{ advertisement.id }}">
            <input class="button is-danger is-light" type="submit" value="Delete">
        </form>
    </div>
</div>
{% endblock top-menu-left %}


{% block main %}
<div class="card p-3">
    <div class="card-header">
        <div class="title card-header-title">
            {{ advertisement.subject }}
        </div>
    </div>
    <div class="card-content p-4">
        {{ advertisement.text }}
    </div>
    <div class="card-footer p-4">
        <div class="card-footer-item has-text-primary">
            {{ advertisement.cost }}
        </div>
        <div class="card-footer-item">
            {{ advertisement.created }}
        </div>
    </div>
</div>
{% endblock main %}

ads/templates/ads/advertisement_edit.html
{% extends 'ads/layout/base.html' %}

{% block title %}Edit advertisement{% endblock title %}

{% block header %}Edit advertisement {{ advertisement.subject }}{% endblock header %}

{% block main %}
<form method="post" class="p-6">
    {% csrf_token %}

    <div class="field">
        <label class="label" for="subject">Subject</label>
        <div class="control">
            <input class="input" type="text" name="subject" id="subject" value="{{ advertisement.subject }}">
        </div>
    </div>

    <div class="field">
        <label class="label" for="text">Text</label>
        <div class="control">
            <textarea class="textarea" name="text" id="text" cols="30" rows="10">{{ advertisement.text }}</textarea>
        </div>
    </div>

    <div class="field">
        <label class="label" for="cost">Cost</label>
        <div class="control">
            <input class="input" type="number" name="cost" id="cost" step="0.01" min="0.01" value="{{ advertisement.cost }}">
        </div>
    </div>

    <input type="hidden" name="category" value="{{ advertisement.category.id }}" readonly>

    <div class="field">
        <div class="control">
            <input class="button is-primary" type="submit" value="Submit">
        </div>
    </div>
</form>
{% endblock main %}

ads/templates/ads/advertisements_list.html
{% extends 'ads/layout/base.html' %}

{% block title %}{{ current_category }}{% endblock title %}

{% block header %}Category {{ current_category }}{% endblock header %}

{% block top-menu-left %}
<div class="navbar-item">
    <div class="buttons">
        <a href="{% url 'ads:advertisement_add' current_category %}" class="button is-primary is-light add-ad-button">Add advertisement</a>
    </div>
</div>
{% endblock top-menu-left %}

{% block main %}
{% for ad in object_list %}
<div class="ad-block box">
    <div class="ad-title subtitle"><a href="{% url 'ads:advertisement_detail' category=current_category ad_id=ad.id %}">{{ ad.subject }}</a></div>
    <div class="ad-cost content has-background-primary has-text-white p-1">{{ ad.cost }}</div>
    <div class="buttons">
        <a class="button is-warning is-light" href="{% url 'ads:advertisement_edit' ad_id=ad.id category=current_category %}">Edit</a>
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="ad_id" value="{{ ad.id }}">
            <input class="button is-danger is-light" type="submit" value="Delete">
        </form>
    </div>
</div>
{% endfor %}
{% endblock main %}
{% block footer %}
<footer>
    {% if page_obj %}
    <nav class="bottom-menu">
        <div class="prev-buttons">
            {% if page_obj.has_previous %}
            <a href="{% url 'ads:advertisements_list' category=current_category %}?page=1"><button class="button is-black">To the begining</button></a>
            <a href="{% url 'ads:advertisements_list' category=current_category %}?page={{ page_obj.previous_page_number }}"><button class="button is-dark">Back</button></a>
            {% endif %}
        </div>
        <div class="pages">
            {% if page_obj.paginator.num_pages > 1 %}
            {{ page_obj.number }} out of {{ page_obj.paginator.num_pages }}
            {% endif %}
        </div>
        <div class="next-buttons">
            {% if page_obj.has_next %}
            <a href="{% url 'ads:advertisements_list' category=current_category %}?page={{ page_obj.next_page_number }}"><button class="button is-dark">Forward</button></a>
            <a href="{% url 'ads:advertisements_list' category=current_category %}?page={{ page_obj.paginator.num_pages }}"><button class="button is-black">To the end</button></a>
            {% endif %}
        </div>
    </nav>
    {% endif %}
</footer>
{% endblock footer %}

ads/templates/ads/categories_list.html
{% extends 'ads/layout/base.html' %}

{% block title %}Categories{% endblock title %}

{% block header %}Categories{% endblock header %}

{% block top-menu-left %}
<div class="navbar-item">
    <div class="buttons">
        <a href="{% url 'ads:category_add' %}" class="button is-primary is-light add-cat-button">Add category</a>
    </div>
</div>
{% endblock top-menu-left %}

{% block main %}
{% for cat in cats %}
<div class="cat-block box">
    <div class="cat-title subtitle"><a href="{% url 'ads:advertisements_list' category=cat.name %}?page=1"><h2>{{ cat.name }}</h2></a></div>
    <div class="cat-desc content">{{ cat.desc }}</div>
    <div class="cat-count content has-text-danger-light has-background-dark p-2">{{ cat.advertisement_set.count }} ads</div>
    <div class="buttons">
        <a class="button is-warning is-light" href="{% url 'ads:category_edit' cat.name %}">Edit</a>
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="category" value="{{ cat.id }}">
            <input class="button is-danger is-light" type="submit" value="Delete">
        </form>
    </div>
</div>
{% endfor %}
{% endblock main %}

ads/templates/ads/category_add.html
{% extends 'ads/layout/base.html' %}

{% block title %}Add category{% endblock title %}

{% block header %}Add category{% endblock header %}

{% block main %}
<form method="post" class="p-6">
    {% csrf_token %}

    <div class="field">
        <label class="label" for="name">Name</label>
        <div class="control">
            <input class="input" type="text" name="name" id="name">
        </div>
    </div>

    <div class="field">
        <label class="label" for="desc">Description</label>
        <div class="control">
            <textarea class="textarea" name="desc" id="desc" cols="30" rows="10"></textarea>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <input class="button is-primary" type="submit" value="Submit">
        </div>
    </div>
</form>
{% endblock main %}

ads/templates/ads/category_edit.html
{% extends 'ads/layout/base.html' %}

{% block title %}Edit category{% endblock title %}

{% block header %}Edit category {{ category.name }}{% endblock header %}

{% block main %}
<form method="post" class="p-6">
    {% csrf_token %}

    <div class="field">
        <label class="label" for="name">Name</label>
        <div class="control">
            <input class="input" type="text" name="name" id="name" value="{{ category.name }}">
        </div>
    </div>

    <div class="field">
        <label class="label" for="desc">Description</label>
        <div class="control">
            <textarea class="textarea" name="desc" id="desc" cols="30" rows="10">{{ category.desc }}</textarea>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <input class="button is-primary" type="submit" value="Submit">
        </div>
    </div>
</form>
{% endblock main %}

ads/templates/ads/home_page.html
Здесь отображаются все твои объявления

ads/templates/ads/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'ads/css/bulma.min.css' %}">
    <link rel="stylesheet" href="{% static 'ads/css/styles.css' %}">
</head>
<body>
    <header>
        <nav class="navbar top-menu has-background-light">
            <div class="navbar-brand">
                <h1 class="title navbar-item">{% block header %}{% endblock header %}</h1>
            </div>
            {% block top-menu %}
            <div class="navbar-menu is-active">
                <div class="navbar-start">{% block top-menu-left %}{% endblock top-menu-left %}</div>
                <div class="navbar-end">
                    {% block top-menu-right %}
                    <div class="navbar-item">
                        <div class="buttons">
                            <a class="button is-link home-button">Home</a>
                            <a class="button is-primary registration-button">Register</a>
                            <a class="button is-light login-button">Login</a>
                            <a class="button is-danger quit-button">Quit</a>
                        </div>
                    </div>
                    {% endblock top-menu-right %}
                </div>
            </div>
            {% endblock top-menu %}
        </nav>
    </header>
    <main>
        <aside class="menu">
        {% block navigator %}
        <nav>
            <a class="menu-label button is-black has-text-white mt-4" href="{% url 'ads:categories_list' %}"><h2>Main&nbsp;Page</h2></a>
            <ul class="menu-list">
                {% for cat in navigator.categories %}
                {% if current_category == cat.name %}
                <a class="navigator-link has-text-light has-background-grey" href="{% url 'ads:advertisements_list' cat.name %}"><li>{{ cat.name|capfirst }}</li></a>
                {% else %}
                <a class="navigator-link has-text-black" href="{% url 'ads:advertisements_list' cat.name %}"><li>{{ cat.name|capfirst }}</li></a>
                {% endif %}
                {% endfor %}
            </ul>
        </nav>
        {% endblock navigator %}
        </aside>
        <article>
            {% block main %}{% endblock main %}
        </article>
    </main>
    {% block footer %}{% endblock footer %}
</body>
</html>